import { Project } from "../models/project";

export const projectData : Project[] = [
  
    {
      "img": 'https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(117).jpg',
      "id":"OPX68YEO4CC",
		"name": "Nec Corp.",
		"description": "Decription of the projects", 
		"number_of_applications": 775,
		"critical_violations": 21,
		"robustness_index": 67,
		"security_index": 382,
        "efficiency_index" :125,
		"changeability_index": 5,
		"transferability_index": 3,
		"technical_size": 838471
    },
    {
      img: 'https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(98).jpg',
      description: 'Image 22222',
      "id": "QZY92CLP3TJ",
		"name": "Aliquam Incorporated",
		"number_of_applications": 113,
        "efficiency_index" :105,
		"critical_violations": 97,
		"robustness_index": 106,
		"security_index": 122,
		"changeability_index": 1,
		"transferability_index": 23,
		"technical_size": 609595
    },
    {
      img: 'https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(131).jpg',
      "id": "ILJ72PXZ3DK",
		"name": "Duis Company",
		"description": "Description",
		"number_of_applications": 603,
		"critical_violations": 13,
		"robustness_index": 110,
		"security_index": 229,
		"changeability_index": 10,
		"transferability_index": 79,
		"technical_size": 984961,
        "efficiency_index" :105,
    },
    {
      img: 'https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(123).jpg',
      "id": "KOT17MSV2KX",
		"name": "Ullamcorper Ltd",
		"description":"Description of project",
		"number_of_applications": 343,
		"critical_violations": 97,
		"robustness_index": 1,
		"security_index": 384,
		"changeability_index": 51,
		"transferability_index": 32,
		"technical_size": 577265,
        "efficiency_index" :105,
    },
    {
      img: 'https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(118).jpg',
      "id": "LQG54ICR9ZD",
      "name": "Aliquet Phasellus Fermentum LLP",
      "description": "Description of project",
      "number_of_applications": 716,
      "critical_violations": 39,
      "robustness_index": 107,
      "security_index": 108,
      "changeability_index": 74,
      "transferability_index": 56,
      "technical_size": 24816,
      "efficiency_index" :78,
    },
    {
      img: 'https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(128).jpg',
      "id": "WRW58YLT1BD",
		"name": "Arcu Vestibulum Ut Industries",
		"description": "Description of project",
		"number_of_applications": 203,
		"critical_violations": 86,
		"robustness_index": 39,
		"security_index": 217,
		"changeability_index": 4,
		"transferability_index": 16,
		"technical_size": 206395,
        "efficiency_index" :73,
    },
    {
      img: 'https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(132).jpg',
      "id": "MQJ82IHN9AQ",
      "name": "Aenean Ltd",
      "description":"Description of project" ,
      "number_of_applications": 495,
      "critical_violations": 97,
      "robustness_index": 101,
      "security_index": 173,
      "changeability_index": 63,
      "transferability_index": 45,
      "technical_size": 194687,
      "efficiency_index" :73,
    },
    {
      img: 'https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(115).jpg',
      "id": "ECS54BUS7DQ",
		"name": "Aliquam Erat Volutpat Limited",
		"description": "Description of project",
		"number_of_applications": 688,
		"critical_violations": 34,
		"robustness_index": 195,
		"security_index": 9,
		"changeability_index": 55,
		"transferability_index": 47,
		"technical_size": 570368,
        "efficiency_index" :73,
    },
    {
      img: 'https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(133).jpg',
      "id": "ZRW75XCL4EK",
      "name": "Ut Nec Urna LLP",
      "description": "Description of project",
      "number_of_applications": 709,
      "critical_violations": 18,
      "robustness_index": 148,
      "security_index": 8,
      "changeability_index": 1,
      "transferability_index": 99,
      "technical_size": 341034,
      "efficiency_index" :73,
    },
    {
      img: 'https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(123).jpg',
      "id": "ALY19DDZ4OD",
		"name": "Nulla In Ltd",
		"description":"Description of project",
		"number_of_applications": 492,
		"critical_violations": 22,
		"robustness_index": 98,
		"security_index": 399,
		"changeability_index": 78,
		"transferability_index": 15,
		"technical_size": 459588,
        "efficiency_index" :43,
    },
    {
      img: 'https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(118).jpg',
      "id": "BUO93LLW9RZ",
		"name": "At Inc.",
		"description": "Description of project",
		"number_of_applications": 508,
		"critical_violations": 86,
		"robustness_index": 77,
		"security_index": 353,
		"changeability_index": 84,
		"transferability_index": 26,
		"technical_size": 6932,
        "efficiency_index" :93,
    },
    {
      img: 'https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(128).jpg',
      "id": "PJX63GOM8SA",
		"name": "Feugiat Limited",
		"description": "Description of project",
		"number_of_applications": 579,
		"critical_violations": 39,
		"robustness_index": 178,
		"security_index": 363,
		"changeability_index": 64,
		"transferability_index": 48,
		"technical_size": 77934,
        "efficiency_index" :36,
    },
    {
      img: 'https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(117).jpg',
      "id": "MZB62HER6BW",
      "name": "Lorem Fringilla Consulting",
      "description": "Description of project",
      "number_of_applications": 397,
      "critical_violations": 28,
      "robustness_index": 94,
      "security_index": 73,
      "changeability_index": 71,
      "transferability_index": 97,
      "technical_size": 866948,
      "efficiency_index" :23,
    },
    {
      img: 'https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(98).jpg',
      "id": "LRZ49VGV5TP",
		"name": "Tortor Integer Aliquam Inc.",
		"description": "Description of project",
		"number_of_applications": 744,
		"critical_violations": 54,
		"robustness_index": 78,
		"security_index": 360,
		"changeability_index": 19,
		"transferability_index": 9,
		"technical_size": 398236,
        "efficiency_index" :43,
    },
    {
      img: 'https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(131).jpg',
      "id": "WDT33JAC6XN",
		"name": "Scelerisque Neque Corp.",
		"description": "Description of project",
		"number_of_applications": 778,
		"critical_violations": 71,
		"robustness_index": 175,
		"security_index": 13,
		"changeability_index": 6,
		"transferability_index": 85,
		"technical_size": 898191,
        "efficiency_index" :37,
    },
    {
      img: 'https://mdbootstrap.com/img/Photos/Horizontal/Nature/12-col/img%20(123).jpg',
      "id": "CBS25XPG1ZU",
		"name": "Imperdiet Erat Institute",
		"description": "Description of project",
		"number_of_applications": 846,
		"critical_violations": 30,
		"robustness_index": 37,
		"security_index": 311,
		"changeability_index": 52,
		"transferability_index": 31,
		"technical_size": 518858,
        "efficiency_index" :87,
    }
];